### ISSUE TITLE
cherivis won't build with current llvm-cheri

### ISSUE THREAD

**Issue by tmarkettos** [CTSRD-CHERI/CheriVis#3]
Ubuntu 14.04, fresh GNUstep installed from source via http://wiki.gnustep.org/index.php/GNUstep_under_Ubuntu_Linux but with CHERI llvm and clang used.

cherivis build fails with:

atm26@ubuntu:~/cherivis$ make
This is gnustep-make 2.6.7. Type 'make print-gnustep-make-help' for help.
Making all for app CheriVis...
 Compiling file CVDisassembler.mm ...
warning: unknown warning option '-Wno-maybe-uninitialized'; did you mean
      '-Wno-uninitialized'? [-Wunknown-warning-option]
CVDisassembler.mm:5:10: fatal error: 'llvm/Support/StringRefMemoryObject.h' file
      not found
#include "llvm/Support/StringRefMemoryObject.h"
         ^
1 warning and 1 error generated.
make[3]: *** [obj/CheriVis.obj/CVDisassembler.mm.o] Error 1
make[2]: *** [internal-app-run-compile-submake] Error 2
make[1]: *** [CheriVis.all.app.variables] Error 2
make: *** [internal-all] Error 2

StringRefMemoryObject has recently been removed from llvm.  If I [copy it](https://raw.githubusercontent.com/trailofbits/mcsema/master/llvm-3.5/include/llvm/Support/StringRefMemoryObject.h) back into the local tree I get:

In file included from CVDisassembler.mm:5:
./StringRefMemoryObject.h:32:28: error: only virtual member functions can be
      marked 'override'
  uint64_t getBase() const override { return Base; }
                           ^~~~~~~~~
./StringRefMemoryObject.h:35:52: error: only virtual member functions can be
      marked 'override'
  int readByte(uint64_t Addr, uint8_t *Byte) const override;
                                                   ^~~~~~~~
./StringRefMemoryObject.h:36:67: error: non-virtual member function marked
      'override' hides virtual member function
  int readBytes(uint64_t Addr, uint64_t Size, uint8_t *Buf) const override;
                                                                  ^
/home/atm26/llvm/include/llvm/Support/MemoryObject.h:47:20: note: hidden
      overloaded virtual function 'llvm::MemoryObject::readBytes' declared here:
      type mismatch at 1st parameter ('uint8_t *' (aka 'unsigned char *') vs
      'uint64_t' (aka 'unsigned long'))
  virtual uint64_t readBytes(uint8_t *Buf, uint64_t Size,
                   ^
CVDisassembler.mm:78:24: error: variable type 'llvm::StringRefMemoryObject' is
      an abstract class
        StringRefMemoryObject memoryObject(StringRef((const char*)&anIns...
                              ^
/home/atm26/llvm/include/llvm/Support/MemoryObject.h:47:20: note: unimplemented
      pure virtual method 'readBytes' in 'StringRefMemoryObject'
  virtual uint64_t readBytes(uint8_t *Buf, uint64_t Size,
                   ^
/home/atm26/llvm/include/llvm/Support/MemoryObject.h:56:26: note: unimplemented
      pure virtual method 'getPointer' in 'StringRefMemoryObject'
  virtual const uint8_t *getPointer(uint64_t address, uint64_t size) const = 0;
                         ^
/home/atm26/llvm/include/llvm/Support/MemoryObject.h:63:16: note: unimplemented
      pure virtual method 'isValidAddress' in 'StringRefMemoryObject'
  virtual bool isValidAddress(uint64_t address) const = 0;
               ^
1 warning and 4 errors generated.

**Comment by davidchisnall** [comment]
This is a known issue.  I'm currently modifying CheriVis to use the trace library so that the updates will only need to happen in one place.

**Comment by davidchisnall** [comment]
This was fixed a while ago and the latest version is now in FreeBSD ports.  Packages should appear in the next 24 hours.
